#!/usr/bin/bash
if [ $# -eq 0 ]; then
	echo -e "\nUsage: $0 [option] <filename or directory>\n\nOptions\n\t-t : add traceroute result\n"
	exit -1
else
	if [ $# -eq 2 ]; then
		input=$2
	else
		input=$1
	fi

	if [ -d $input ]; then
		dir=$(pwd)
		cd $input
		file=($(ls))
		for(( i=0; ${#file[$i]}>0; i++ ))
		do
			apk_ip_hunter ${file[$i]}
		done
		cd $dir
	else
		if [ "$(echo $input | grep -Eo ".apk")" = ".apk" ] || [ "$(echo $input | grep -Eo ".zip")" = ".zip" ]; then
			mkdir unzipped_apk
			cd unzipped_apk
			if [ "${input:1}" = "/" ]; then
				unzip -P "infected" $input 1>/dev/null 
			else
				unzip -P "infected" ../$input 1>/dev/null
			fi
			echo "============================================================="
			echo -e "\tapk/zip file : $input"
			file=($(ls))
			for(( i=0; ${#file[$i]}>0; i++ ))
			do
				apk_ip_hunter ${file[$i]}
			done
			cd ..
			rm -rf unzipped_apk
		else
			ip=$(strings $input | grep -Eo "[1-9]{1}[0-9]{0,2}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}")
			if [ ${#ip} -eq 0 ]; then
				#echo -e "\nThere is no ip detected\n"
				exit -1
			fi
			echo "------------------------------------------------------------"
			echo -e "	filename : $input"
			echo "------------------------------------------------------------"
			echo -e "\nDetected ip patterns\n"
			echo -e "${ip/ /\n}\n"
			if [ "$1" = "-t" ]; then
				echo -e "\nTraceroute Result\n"
				traceroute $ip
				echo ""
			fi
		fi
	fi
fi
unset file
unset files
unset ip
unset ip_raw
unset port
